[package]
name = "codecrafters-interpreter"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.96"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
crossterm = "0.29.0"
thiserror = "1.0.38"                             # error handling

[lints.rust]
elided_lifetimes_in_paths = "warn"

[features]
init-vars = []
str-cmp = []
str-num-concat = []
